### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by programgames** [MultimodLabs/Jei-Fast-Search#1]
TODO : 

- [ ] Add readme ( License, what it is, link to wiki , link to cursrforge modrinth, usage, dev setup ) 
- [ ] Create multiple branch corresponding to Minecraft versions
- [ ] Push to Curseforge and Modrinth
- [ ] Add A maven link
- [ ] Clean logo, pack.mcmeta, mods.toml , MetaInf
- [ ] Use gradle.properties
- [ ] Add some gradles scripts ( auto upload ... ) 
- [ ] Moove mod logic into an Handler
